# The workflow to install the package
name: Install

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [ "Publish" ]
    types:
      - completed

jobs:
  install-npm:
    # Run on multiple operating systems and Node.js versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [20, 22, 24]
      fail-fast: false

    steps:
      # Checkout the repository
      - uses: actions/checkout@v6

      # Set up Node.js with the specified version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Generate package.json file"
        working-directory: html
        run: npm init -y

      - name: "Install Nepali Date Converter"
        working-directory: html
        run: npm install @remotemerge/nepali-date-converter

      - name: "List installed packages"
        working-directory: html
        run: npm list --depth=0

  install-yarn:
    # Run on multiple operating systems and Node.js versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node-version: [20, 22, 24]
      fail-fast: false

    steps:
      # Checkout the repository
      - uses: actions/checkout@v6

      # Set up Node.js with the specified version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Generate package.json file"
        working-directory: html
        run: npm init -y

      - name: "Install Nepali Date Converter"
        working-directory: html
        run: yarn add @remotemerge/nepali-date-converter

      - name: "List installed packages"
        working-directory: html
        run: yarn list --depth=0

  install-pnpm:
    # Run on multiple operating systems and Node.js versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [20, 22, 24]
      fail-fast: false

    steps:
      # Checkout the repository
      - uses: actions/checkout@v6

      # Set up Node.js with the specified version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Generate package.json file"
        working-directory: html
        run: pnpm init

      - name: "Install Nepali Date Converter"
        working-directory: html
        run: pnpm add @remotemerge/nepali-date-converter

      - name: "List installed packages"
        working-directory: html
        run: pnpm list --depth=0

  install-bun:
    # Run on multiple operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false

    steps:
      # Checkout the repository
      - uses: actions/checkout@v6

      # Set up Bun
      - uses: oven-sh/setup-bun@v2

      - name: "Generate package.json file"
        working-directory: html
        run: bun init -y

      - name: "Install Nepali Date Converter"
        working-directory: html
        run: bun add @remotemerge/nepali-date-converter

      - name: "List installed packages"
        working-directory: html
        run: bun pm ls
