# The workflow to install the package
name: Install

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [ "Publish" ]
    types:
      - completed

jobs:
  install:
    # Run on multiple operating systems and Node.js versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [18, 20, 22]
      fail-fast: false

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js with the specified version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate package.json file
        run: npm init -y

      - name: Install Nepali Date Converter
        run: npm install @remotemerge/nepali-date-converter

      - name: List installed packages
        run: npm list --depth=0
