# The workflow to publish package
name: Publish

# Controls when the workflow will run
on:
  release:
    types: [ created ]
    branches: [ main ]

jobs:
  publish:
    # OS to run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Install dependencies"
        run: npm install

      - name: "Build project"
        run: npm run package

      - name: "Copy readme doc"
        run: \cp README.md ./dist/README.md

      # publish to NPM
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
