# The workflow to publish the package
name: Publish

# Controls when the workflow will run
on:
  release:
    types: [ created ] # Trigger on new releases
    branches: [ main ] # Only on the main branch

jobs:
  publish:
    # Run on the latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v6

      # Set up Bun
      - uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        working-directory: html
        run: bun install

      - name: "Build project"
        working-directory: html
        run: bun run build

      - name: "Publish the package to npm"
        working-directory: html
        run: bun publish ./dist --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
