# The workflow to publish the package
name: Publish

# Controls when the workflow will run
on:
  release:
    types: [ created ] # Trigger on new releases
    branches: [ main ] # Only on the main branch

jobs:
  publish:
    # Run on the latest Ubuntu
    runs-on: ubuntu-latest

    # Set default values for the jobs
    defaults:
      run:
        shell: bash
        working-directory: ./html

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js with the LTS version
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish the package to npm
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
