name: Test

# Trigger the workflow on pull requests
on: [ pull_request ]

jobs:
  test:
    # Run on multiple operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-latest, macos-latest ]
      fail-fast: false

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7.0.1

      - name: "Set up Bun version 2.2.0"
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6

      - name: "Install dependencies"
        working-directory: html
        run: bun install --ignore-scripts

      - name: "Build project"
        working-directory: html
        run: bun run build

      - name: "Create data file"
        working-directory: html
        run: bun x shx cp __tests__/data.dist.json __tests__/data.json

      - name: "Run Tests"
        working-directory: html
        run: bun run test
